name: digital_paint
description: "A DigitalPaint project"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter_svg: ^2.0.0
  video_player: ^2.0.0
  vector_math: ^2.1.0
  image: ^4.0.0
  path: ^1.9.1
  flutter_colorpicker: ^1.0.0
  file_selector: ^1.0.3
  file_selector_web: ^0.9.4+2
  image_picker: ^1.0.4
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  fl_chart: 0.68.0
  google_fonts: 6.1.0
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5
  provider: 6.1.2
  http: '>=1.0.0'
  uuid: '>=3.0.0'
  archive: ^4.0.7
  file_picker: ^10.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
