name: dreamflow
description: "A DreamFlow project"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter_svg: ^2.0.0
  video_player: ^2.0.0
  vector_math: ^2.1.0
  image: ^4.0.0
  path: ^1.8.0
  flutter_colorpicker: ^1.0.0
  file_selector: ^1.0.3
  file_selector_web: ^0.9.4+2
  image_picker: ^1.0.4
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  fl_chart: 0.68.0
  google_fonts: 6.1.0
  shared_preferences: 2.3.2
  path_provider: 2.1.4
  provider: 6.1.2
  http: '>=1.0.0'
  uuid: '>=3.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
